### PR TITLE
Fix Dynamic content rendering and spacing issues

### LINKED ISSUE #15209: Dynamic Content - Elements always come with default padding thats not removable in the builder
### Mautic Series

6.0.x series

### Mautic installed version

6.0.0

### Way of installing

I downloaded a release from https://www.mautic.org/mautic-releases

### PHP version

8.3

### What browsers are you seeing the problem on?

_No response_

### What happened?

Per default, Dynamic elements always come with a default 25px left/right & 10px top/bottom padding. 
```html
<mj-text 
data-gjs-type="dynamic-content" data-slot="dynamicContent" data-param-dec-id="2" 
style="padding-top:10px;padding-bottom:10px;padding-right:25px;padding-left:25px;font-size:13px;align:left;display:block;">Dynamic Content 2
</mj-text>
``` 

You can remove the padding using the MJML-Code Editor in the Email itself, but thats not enough. Upon saving the email, you can check the database `emails.custom_html` for the HTML of the email and see, that the padding is still there:

```
<td align="left" style="font-size:0px;padding:10px 25px;word-break:break-word;">
<div style="font-family:Ubuntu, Helvetica, Arial, sans-serif;font-size:13px;line-height:1;text-align:left;color:#000000;">{dynamiccontent="Dynamic Content 2"}</div>
</td>
``` 

As you can see, there still exists an `padding:10px 25px` and it will be sent out like this.
If you remove that padding directly from the database, re-open the email in the builder and save, the padding will be again.

This behaviour of default padding has been noted here back when we switched from now legacy to GrapesJS Builder: https://github.com/mautic/mautic/pull/10114#pullrequestreview-730096078.

### How can we reproduce this issue?

1. Create an email
2. Drag a Dynamic Content element into the Builder
3. Open the MJML-Code Editor in the Builder
4. Find the Dynamic Content, Remove the 10px 25px padding
5. Save the Email
6. Send out the email & open it
7. See that the content will still have said padding

### Relevant log output

```shell
-
```

### Code of Conduct

- [x] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

### PR DESCRIPTION
**Pull request by patrykgruszka**
Fix dynamic content functionality in the GrapeJS Mautic preset:
- Fix dynamic content MJML rendering by restructuring the DOM component rendering logic
- Prevent dynamic content from disappearing after save by removing problematic command handlers
- Add option to edit the padding of the dynamic content element:
image

Closes [#15209](https://github.com/mautic/mautic/issues/15209)

## Test plan
- Create a new email with dynamic content blocks
- Verify dynamic content displays correctly in the editor
- Save the email and confirm dynamic content persists
- Test MJML rendering of dynamic content blocks (preview the email or send it)
- Verify no console errors related to dynamic content commands

## How to test with Mautic:

<details>
<summary><strong>Option 1: Developer Setup (Recommended for Testing)</strong></summary>

This approach allows you to work with the latest source code directly and make additional changes if needed.

#### Prerequisites

- Git installed
- Node.js and npm installed
- Mautic instance running locally
- Terminal/command line knowledge

#### Steps

1. **Clone the repositories side by side**

   Navigate to your projects directory (e.g., `~/projects`) and clone both repos:

   ```bash
   cd ~/projects

   # Clone Mautic (if you don't have it yet)
   git clone https://github.com/mautic/mautic.git

   # Clone the preset with the fix branch
   git clone --branch MTC-8602_dwc-padding-issues git@github.com:patrykgruszka/grapesjs-preset-mautic.git
   ```

   Your directory structure should look like:
   ```
   ~/projects/
   ├── mautic/
   └── grapesjs-preset-mautic/
   ```

2. **Update Mautic to use local preset**

   Edit `mautic/plugins/GrapesJsBuilderBundle/Assets/library/js/builder.service.js`:

   - **Comment out** lines 14-15 (the npm package imports):
     ```js
     // import contentService from 'grapesjs-preset-mautic/dist/content.service';
     // import grapesjsmautic from 'grapesjs-preset-mautic';
     ```

   - **Uncomment** lines 20-21 (the local imports):
     ```js
     import contentService from '../../../../../../grapesjs-preset-mautic/src/content.service';
     import grapesjsmautic from '../../../../../../grapesjs-preset-mautic/src';
     ```

   Full diff:
   ```diff
   -import contentService from 'grapesjs-preset-mautic/dist/content.service';
   -import grapesjsmautic from 'grapesjs-preset-mautic';
   +// import contentService from 'grapesjs-preset-mautic/dist/content.service';
   +// import grapesjsmautic from 'grapesjs-preset-mautic';
    import editorFontsService from 'grapesjs-preset-mautic/dist/editorFonts/editorFonts.service';
    import StorageService from './storage.service';

    // for local dev
   -// import contentService from '../../../../../../grapesjs-preset-mautic/src/content.service';
   -// import grapesjsmautic from '../../../../../../grapesjs-preset-mautic/src';
   +import contentService from '../../../../../../grapesjs-preset-mautic/src/content.service';
   +import grapesjsmautic from '../../../../../../grapesjs-preset-mautic/src';
   ```

3. **Build the plugin**

   ```bash
   cd mautic/plugins/GrapesJsBuilderBundle
   npm run rebuild
   ```

4. **Clear Mautic cache**

   ```bash
   cd mautic

   # For development
   php bin/console cache:clear

   # Or if using DDEV
   ddev php bin/console cache:clear
   ```

5. **Test the changes**

   - Open your Mautic email builder: `https://your-mautic-instance/s/emails`
   - Create a new email and add dynamic content
   - Save the email
   - Verify that dynamic content persists after save
   - Test MJML rendering by switching to code view

</details>

<details>
<summary><strong>Option 2: Pre-built Distribution File (For Non-Technical Users)</strong></summary>

This approach uses a pre-built version of the preset without needing Node.js or build tools.

#### Prerequisites
- Mautic instance running locally

#### Steps

1. **Download the pre-built file**

   Download the builder file from the release:
   - [builder.js](https://github.com/user-attachments/files/26829936/builder.js)

2. **Replace the file in your Mautic installation**

   Navigate to your Mautic directory and replace the builder file:
   ```bash
   cp ~/Downloads/builder.js \
     mautic/plugins/GrapesJsBuilderBundle/Assets/library/js/dist/builder.js
   ```

   Or manually:
   - Open file explorer/finder
   - Navigate to `mautic/plugins/GrapesJsBuilderBundle/Assets/library/js/dist/`
   - Replace `builder.js` with the downloaded file

3. **Clear Browser cache**

4. **Test the changes**

</details>

### CODE REVIEW

File: src/dynamicContent/dynamicContent.domcomponents.js [hunk 1]
```diff
@@ -1,37 +1,44 @@
...
 
 export default class DynamicContentDomComponents {
   dcService;
 
   static addDynamicContentType(editor) {
     const dc = editor.DomComponents;
-    const baseTypeName = ContentService.isMjmlMode(editor) ? 'mj-text' : 'text';
-    const tagName = ContentService.isMjmlMode(editor) ? 'mj-text' : 'div';
-    const baseType = dc.getType(baseTypeName);
+    const baseType = dc.getType('mj-text');
```
Comment (hluchas) [inline src/dynamicContent/dynamicContent.domcomponents.js]: Non-MJML mode is silently dropped — potentially a breaking change?

File: src/dynamicContent/dynamicContent.domcomponents.js [hunk 2]
```diff
@@ -1,37 +1,44 @@
...
     const baseModel = baseType.model;
 
-    const dynamicContentModel = {
-      name: 'Dynamic Content',
-      tagName,
-      draggable: '[data-gjs-type=cell],[data-gjs-type=mj-column]',
-      droppable: false,
-      editable: false,
-      stylable: false,
```
Comment (hluchas) [inline src/dynamicContent/dynamicContent.domcomponents.js:20]: Legacy DC components in saved emails don't pick up the new model
Verified locally:

DC blocks inserted before the fix keep stylable: false and tagName: 'div' in their serialized model in the DB. After deploying the fix, those blocks still don't show padding controls; the user must delete and re-insert.

Since the PR targets an existing Mautic install with emails already in the wild, this surprises users ("I deployed the fix but my DC still has no padding").

File: src/dynamicContent/dynamicContent.domcomponents.js [hunk 3]
```diff
@@ -1,37 +1,44 @@
...
-    const baseTypeName = ContentService.isMjmlMode(editor) ? 'mj-text' : 'text';
-    const tagName = ContentService.isMjmlMode(editor) ? 'mj-text' : 'div';
-    const baseType = dc.getType(baseTypeName);
+    const baseType = dc.getType('mj-text');
     const baseModel = baseType.model;
 
-    const dynamicContentModel = {
-      name: 'Dynamic Content',
-      tagName,
-      draggable: '[data-gjs-type=cell],[data-gjs-type=mj-column]',
```
Comment (hluchas) [inline src/dynamicContent/dynamicContent.domcomponents.js:17]: Not sure about this, but could this be hidden breaking change?
[data-gjs-type=cell] (the non-MJML HTML table cell target) is removed from draggable.

**Review by hluchas — APPROVED** [review]
It works. Some comments added.

File: src/dynamicContent/dynamicContent.domcomponents.js (hunk 1 above)
Comment (patrykgruszka) [reply src/dynamicContent/dynamicContent.domcomponents.js]: Is it possible to use the GJS builder with HTML email template? I've removed this because I thought it is a dead code. 

But good point, this change should at least be mentioned in the PR description.

File: src/dynamicContent/dynamicContent.domcomponents.js (hunk 2 above)
Comment (patrykgruszka) [reply src/dynamicContent/dynamicContent.domcomponents.js:20]: I've tried to reproduce this issue, but without success. Do you see anything that I'm doing differently than in your case? Seems to work fine:

1. I've added DC with old GJS scipt
2. Rebuild GJS with PR changes
3. Reloaded email and added padding
4. Verified on email preview

https://github.com/user-attachments/assets/e23ef3f7-5be1-49c6-8665-2d8a0891d120

Comment (hluchas) [reply src/dynamicContent/dynamicContent.domcomponents.js:20]: You are right. My mistake.
Blocks in stored emails inherit the new model automatically. No migration needed.

I'm sorry about this.

File: src/dynamicContent/dynamicContent.domcomponents.js (hunk 3 above)
Comment (patrykgruszka) [reply src/dynamicContent/dynamicContent.domcomponents.js:17]: Yes, this is the same case as the HTML support for email builder in general.

File: src/dynamicContent/dynamicContent.domcomponents.js (hunk 1 above)
Comment (hluchas) [reply src/dynamicContent/dynamicContent.domcomponents.js]: I did some research and is seems to be not really dead code.

It's hard to guess without telemetry, but email-html mode in Mautic is still available for custom HTML templates (theme without MJML source). Anyone with an email template that doesn't start with <mjml> opens the editor in email-html mode and needs working DC support.

#	Scenario	Likelihood
1
Custom email theme imported from Mailchimp / Litmus / hand-written — email.html.twig without an <mjml> wrapper
High in B2B, agencies, brands with custom identity
2
Theme inherited from Mautic 3.x / 4.x without migration to MJML
High on older installations
3
Built-in Mautic themes that aren't MJML (some are, some aren't — depends on version)
Medium
4
Email created before the MJML builder was introduced, still being edited today
Medium
5
Duplicate of an older email whose custom_mjml is NULL in the DB
Low/medium
6
Server-side MJML rendering failed, Mautic fell back to HTML export
Low

Comment (patrykgruszka) [reply src/dynamicContent/dynamicContent.domcomponents.js]: You're right, I've replicated this, thanks!

Comment (patrykgruszka) [reply src/dynamicContent/dynamicContent.domcomponents.js]: I've brought back HTML support in the Dynamic Content block

File: src/dynamicContent/dynamicContent.domcomponents.js (hunk 3 above)
Comment (patrykgruszka) [reply src/dynamicContent/dynamicContent.domcomponents.js:17]: I've added this back in the HTML support part

**Review by hluchas — APPROVED** [review]
Thank you for your fix. Looks good now.

**Review by MadlenF — APPROVED** [review]
Works as described! 
Glad there is finally a solution for it, thanks @patrykgruszka  🥳
